//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolsLanguage.ModelDB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientService = new HashSet<ClientService>();
            this.TagOfClient = new HashSet<TagOfClient>();
            this.VisitInfo = new HashSet<VisitInfo>();
        }

        [Required(ErrorMessage = "Идентификатор пользователя не установлен")]
        public int ID { get; set; }
        [Required(ErrorMessage = "Не указано имя пользователя")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Недопустимая длина Имени")]
        [RegularExpression(@"[a-zA-Zа-яА-Я -]+", ErrorMessage = "Недопустимые знаки")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Не указано Фамилия пользователя")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Недопустимая длина Фамилии")]
        [RegularExpression(@"[a-zA-Zа-яА-Я -]+", ErrorMessage = "Недопустимые знаки")]
        public string LastName { get; set; }
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Недопустимая длина Отчества")]
        [RegularExpression(@"[a-zA-Zа-яА-Я -]+", ErrorMessage = "Недопустимые знаки")]
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        [RegularExpression(@"[\w]+@[\w]+[.]{1}[\w]+", ErrorMessage = "Неправильный Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Телефон не введен")]
        [RegularExpression(@"[0-9\-\+\(\)]+\s{1}", ErrorMessage = "Неправильный телефон")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Пол не указан")]
        public string GenderCode { get; set; }
        public string PhotoPath { get; set; }

        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagOfClient> TagOfClient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitInfo> VisitInfo { get; set; }
    }
}
